version: '2'

services:
  docker-gen:
    image: jwilder/docker-gen
    container_name: docker-gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    volumes_from:
      - nginx
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=docker-gen

  dashboard:
    image: nginx
    container_name: dashboard
    volumes:
      - ./dashboard/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=rep.ax
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=rep.ax
      - LETSENCRYPT_EMAIL=dev@nhz.io

  pirl-node:
    image: pirl/pirl-node
    container_name: pirl-node
    volumes:
      - ./volumes/pirl/data:/root/.pirl/pirl
      - ./volumes/pirl/keystore:/root/.pirl/keystore

  pirl-ether-proxy:
    build:
      context: pirl-ether-proxy
    container_name: pirl-ether-proxy
    environment:
      - VIRTUAL_HOST=pirl.rep.ax
      - VIRTUAL_PORT=8080
    volumes:
      - ./pirl-ether-proxy/config.json:/config.json
