version: '2'

services:
  docker-gen:
    image: jwilder/docker-gen
    container_name: docker-gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    volumes_from:
      - nginx
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=docker-gen

  pirl-node:
    image: pirl/pirl-node
    container_name: pirl-node
    environment:
      - ETHERBASE=0x85fe98a34d4e9c3d1163d34efd07eb35e80b7397
    volumes:
      - ./pirl-node/start.sh:/root/start.sh
      - ./volumes/pirl/data:/root/.pirl/pirl
      - ./volumes/pirl/keystore:/root/.pirl/keystore

  pirl-ether-proxy:
    build:
      context: pirl-ether-proxy
    container_name: pirl-ether-proxy
    environment:
      - VIRTUAL_HOST=pirl.rep.ax
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=pirl.rep.ax
      - LETSENCRYPT_EMAIL=dev@nhz.io
    ports:
      - 6589:6589
    volumes:
      - ./pirl-ether-proxy/config.json:/config.json

  pirl-node-fork:
    build:
      context: pirl-node-fork
    container_name: pirl-node-fork
    environment:
      - ETHERBASE=0x85fe98a34d4e9c3d1163d34efd07eb35e80b7397
    volumes:
      - ./pirl-node-fork/start.sh:/root/start.sh
      - ./volumes/pirl-fork/data:/root/.pirl/pirl
      - ./volumes/pirl-fork/keystore:/root/.pirl/keystore


